function sensorXYZ = loadXYZCMFs()
    colorMatchingData = load('T_xyz1931.mat');
    sensorXYZ = struct(...
    	'S', colorMatchingData.S_xyz1931, ...
    	'T', colorMatchingData.T_xyz1931 ...
        );
end