function loadStimuliToView(obj)
    
    % Empty cache
    obj.viewOutlet.emptyCache();
    
    obj.stimulusSize.rows = 440;
    obj.stimulusSize.cols = 880;
    obj.stimulusSize.scaleFactor = 0.3;
    
    % Add new data (these data are generated by the model and are specified in settings values for the
    % current display.
    stimIndex = 1;
    hdrStimRGBdata = zeros(obj.stimulusSize.rows, obj.stimulusSize.cols, 3);
    hdrStimRGBdata(:,:,1) = 1;
    ldrStimRGBdata = ones(obj.stimulusSize.rows, obj.stimulusSize.cols, 3);
    obj.viewOutlet.addToCache(stimIndex, hdrStimRGBdata, ldrStimRGBdata);
    
    % Add new data
    stimIndex = 2;
    hdrStimRGBdata = zeros(obj.stimulusSize.rows, obj.stimulusSize.cols, 3);
    hdrStimRGBdata(:,:,2) = 1;
    ldrStimRGBdata = ones(obj.stimulusSize.rows, obj.stimulusSize.cols, 3);
    obj.viewOutlet.addToCache(stimIndex, hdrStimRGBdata, ldrStimRGBdata);
    
    
    
end

